config/routes.rb
Rails.application.routes.draw do
  resources :suppliers
  resources :addresses
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :supplier
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :suppliers

    validates_presence_of :nome, message: "deve ser preenchido"
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_one :address
  belongs_to :category

  validates_presence_of :name, message: "deve ser preenchido"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :number, :cep, :city, :country, :state, :obs)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:nome)
    end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new 
    @categories = Category.all
  end

  # GET /suppliers/1/edit
  def edit
    @categories = Category.all
    @supplier = Supplier.find(params[:id])
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)
    
    @supplier.address = Address.new(supplier_params[:address])
    binding-pry
    
    validateDate = ValidateDate.new
    dateFoundation = validateDate.validation?(supplier_params[:dateFoundation])

    respond_to do |format|
      if dateFoundation && @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        @supplier.errors[:dateFoundation] << 'Data de fundação ta errada porra' unless dateFoundation
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if dateFoundation && @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        @supplier.errors[:dateFoundation] << 'Data de fundação ta errada porra' unless dateFoundation
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name, :status, :cnpj, :ie, :ci, :dateFoundation, :responsable, :category_id,
                                       address: [:street, :cep, :number, :city, :state, :country, :obs])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :address_street %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :address_number %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep, id: :address_cep %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :address_city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :address_country %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :address_state %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.text_field :obs, id: :address_obs %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>Number</th>
      <th>Cep</th>
      <th>City</th>
      <th>Country</th>
      <th>State</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.number %></td>
        <td><%= address.cep %></td>
        <td><%= address.city %></td>
        <td><%= address.country %></td>
        <td><%= address.state %></td>
        <td><%= address.obs %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Number:</strong>
  <%= @address.number %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @address.cep %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @address.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @address.obs %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :category_nome %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.nome %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @category.nome %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudRubyLES</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier, local: true) do |form| %>
  <% if supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% supplier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :supplier_name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :supplier_status %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj, id: :supplier_cnpj %>
  </div>

  <div class="field">
    <%= form.label :ie %>
    <%= form.text_field :ie, id: :supplier_ie %>
  </div>

  <div class="field">
    <%= form.label :ci %>
    <%= form.text_field :ci, id: :supplier_ci %>
  </div>

  <div class="field">
    <%= form.label :dateFoundation %>
    <%= form.date_select :dateFoundation, id: :supplier_dateFoundation %>
  </div>

  <%= fields_for :address, @supplier.address do |a| %>
    <div class="field">
      <%= a.label :street, 'Rua' %>
      <%= a.text_field :street %>
    </div>

    <div class="field">
      <%= a.label :number %>
      <%= a.text_field :number %>
    </div>
  
    <div class="field">
      <%= a.label :cep %>
      <%= a.text_field :cep %>
    </div>

    <div class="field">
      <%= a.label :city %>
      <%= a.text_field :city %>
    </div>

    <div class="field">
      <%= a.label :state %>
      <%= a.text_field :state %>
    </div>

    <div class="field">
      <%= a.label :country %>
      <%= a.text_field :country %>
    </div>

    <div class="field">
      <%= a.label :obs %>
      <%= a.text_field :obs %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select(:category_id, @categories, :id, :nome) %>
  </div>

  <div class="field">
    <%= form.label :responsable %>
    <%= form.text_field :responsable %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suppliers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Cnpj</th>
      <th>Ie</th>
      <th>Ci</th>
      <th>Datefoundation</th>
      <th>Address</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.name %></td>
        <td><%= supplier.status %></td>
        <td><%= supplier.cnpj %></td>
        <td><%= supplier.ie %></td>
        <td><%= supplier.ci %></td>
        <td><%= supplier.dateFoundation %></td>
        <td><%= supplier.address %></td>
        <td><%= supplier.category %></td>
        <td><%= link_to 'Show', supplier %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
        <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supplier.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @supplier.status %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @supplier.cnpj %>
</p>

<p>
  <strong>Ie:</strong>
  <%= @supplier.ie %>
</p>

<p>
  <strong>Ci:</strong>
  <%= @supplier.ci %>
</p>

<p>
  <strong>Datefoundation:</strong>
  <%= @supplier.dateFoundation %>
</p>

<p>
  <strong>Address:</strong>
  <%= @supplier.address.street %>
</p>

<p>
  <strong>Category:</strong>
  <%= @supplier.category %>
</p>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>